int UNDECLARED_FUNCTION = 0;
int MISSED_SEMICOLON = 1;
int MISSED_OPENING_PARANTHESIS = 2;
int MISSED_CLOSING_PRANATHESIS = 3;
int MISSED_OPEN_CURLY_BRACKET = 4;
int MISSED_CLOSE_CURLY_BRACKET = 5;
int UNDECLARED_VARIABLE = 6;

int typo[7];
char typo_name[][100] = { "UNDECLARED_FUNCTION", "MISSED_SEMICOLON", "MISSED_OPENING_PARANTHESIS", "MISSED_CLOSING_PRANATHESIS", "MISSED_OPEN_CURLY_BRACKET" , "MISSED_CLOSE_CURLY_BRACKET", "UNDECLARED_VARIABLE" };
